import React from 'react'

const Implementation = () => {
    return (
        <div className="w-full text-white bg-[#0f212e] rounded-lg p-[1.5rem] font-semibold shadow-lg">
            <h2 className="text-2xl font-semibold cursor-default">
                Random Number Generation
            </h2>
            <p className="text-[#B1BAD3] text-base mt-4 font-normal cursor-default">
                For each verifiable bet, a client seed, a server seed, a nonce and
                a cursor are used as the input parameters for the
                <a
                    href="#"
                    className="items-center inline-flex ml-1 font-semibold text-white cursor-pointer"
                >
                    random number generation
                    <svg
                        className="ml-2 h-4 w-4 text-[#B1BAD3]"
                        viewBox="0 0 64 64"
                        fill="currentColor"
                    >
                        <path d="M10.823 53.176h42.353V39.941h7.059v20.294H3.765V3.765h20.293v7.058H10.823v42.353Zm28.236-42.353V3.765h21.176V24.94h-7.059v-9.123L27.88 41.115l-4.994-4.995 25.297-25.296H39.06Z" />
                    </svg>
                </a>
                <span className="ml-2 cursor-default">
                    function. This function utilises the cryptographic hash function
                </span>
                <span className="items-center inline-flex ml-1 font-semibold text-white cursor-pointer">
                    HMAC_SHA256
                    <svg
                        className="ml-2 h-4 w-4 font-normal text-[#B1BAD3]"
                        viewBox="0 0 64 64"
                        fill="currentColor"
                    >
                        <path d="M10.823 53.176h42.353V39.941h7.059v20.294H3.765V3.765h20.293v7.058H10.823v42.353Zm28.236-42.353V3.765h21.176V24.94h-7.059v-9.123L27.88 41.115l-4.994-4.995 25.297-25.296H39.06Z" />
                    </svg>
                </span>
                <span className="ml-3">
                    to generate bytes which are then used as the foundation for how
                    we generate provably fair random outcomes on our platform.
                </span>
            </p>

            <div className="bg-[#213743] p-4 rounded mt-4 cursor-default xl:w-full lg:w-[40.7rem] md:w-[38.3rem] font-normal overflow-y-auto scrollbar-thin">
                <pre>
                    {`// Random number generation based on following inputs: serverSeed, clientSeed, nonce and cursor
  function byteGenerator({serverSeed, clientSeed, nonce, cursor}) {
    // Setup curser variables
    let currentRound = Math.floor(cursor / 32);
    let currentRoundCursor = cursor;
    currentRoundCursor -= currentRound * 32;

    // Generate outputs until cursor requirement fullfilled
    while (true) {
        // HMAC function used to output provided inputs into bytes
        const hmac = createHmac('sha256', serverSeed);
        hmac.update(\`\${clientSeed}:\${nonce}:\${currentRound}\`);
        const buffer = hmac.digest();

        // Update curser for next iteration of loop
        while (currentRoundCursor < 32) {
            yield Number(buffer[currentRoundCursor]);
            currentRoundCursor += 1;
        }
        currentRoundCursor = 0;
        currentRound += 1;
    }
};`}
                </pre>
            </div>
            <div className="mt-4">
                <h2 className="font-bold leading-relaxed sm:leading-normal md:leading-loose text-left text-xl sm:text-lg md:text-xl lg:text-2xl flex items-center space-x-2">
                    Server Seed
                </h2>
            </div>
            <p className="mt-4 text-[#B1BAD3] font-normal cursor-default">
                The server seed is generated by our system as a random
                64-character hex string. You are then provided with an encrypted
                hash of that generated server seed before you place any bets. The
                reason we provide you with the encrypted form of the server seed
                is to ensure that the un-hashed server seed cannot be changed by
                the casino operator, and that the player cannot calculate the
                results beforehand.
            </p>

            <p className="mt-4 text-[#B1BAD3] font-normal cursor-default">
                To reveal the server seed from its hashed version, the seed must
                be rotated by the player, which triggers the replacement with a
                newly generated one.
            </p>

            <p className="mt-4 text-[#B1BAD3] font-normal cursor-default">
                From this point you are able to verify that the hashed server seed
                matches that of the un-hashed server seed. This process can be
                verified via our un-hashed server seed function found in the menu
                above.
            </p>
            <div className="mt-8">
                <h2 className="font-bold leading-relaxed sm:leading-normal md:leading-loose text-left text-xl sm:text-lg md:text-xl lg:text-2xl flex items-center space-x-2">
                    Client Seed
                </h2>
                <p className="mt-4 text-[#B1BAD3] font-normal cursor-default">
                    The client seed belongs to the player and is used to ensure they
                    have influence on the randomness of the outcomes generated.
                    Without this component of the algorithm, the server seed alone
                    would have complete leverage over the outcome of each bet.
                </p>

                <p className="mt-4 text-[#B1BAD3] font-normal cursor-default">
                    All players are free to edit and change their client seed
                    regularly to create a new chain of random upcoming outcomes.
                    This ensures the player has absolute control over the generation
                    of the result, similar to cutting the deck at a brick and mortar
                    casino.
                </p>

                <p className="mt-4 text-[#B1BAD3] font-normal cursor-default">
                    During registration, a client seed is created for you by your
                    browser, to ensure your initial experience with the site goes
                    uninterrupted. Whilst this randomly generated client seed is
                    considered suitable, we highly recommend that you choose your
                    own, so that your influence is included in the randomness.
                </p>

                <p className="mt-4 text-[#B1BAD3] font-normal cursor-default">
                    You can do this via the fairness modal.
                </p>
            </div>

            <div className="mt-8">
                <h2 className="font-bold leading-relaxed sm:leading-normal md:leading-loose text-left text-xl sm:text-lg md:text-xl lg:text-2xl flex items-center space-x-2">
                    Nonce
                </h2>
                <p className="mt-4 text-[#B1BAD3] font-normal cursor-default">
                    The nonce is simply a number that increments as every new bet is
                    made. Due to the nature of the SHA256 cryptographic function,
                    this creates a completely new result each time, without having
                    to generate a new client seed and server seed.
                </p>

                <p className="mt-4 text-[#B1BAD3] font-normal cursor-default">
                    The implementation of nonce, ensures we remain committed to your
                    client seed and server seed pair, whilst generating new results
                    for each bet placed.
                </p>
            </div>
            <div className="mt-8">
                <h2 className="font-bold leading-relaxed sm:leading-normal md:leading-loose text-left text-xl sm:text-lg md:text-xl lg:text-2xl flex items-center space-x-2">
                    Cursor (Incremental Number)
                </h2>
                <p className="mt-4 text-[#B1BAD3] font-normal cursor-default">
                    We use 4 bytes of data to generate a single game result, and
                    because SHA256 is limited to 32 bytes, we utilise this
                    implementation of a cursor to give us the ability to create more
                    game events without having to modify our provable fair
                    algorithm.
                </p>

                <p className="mt-4 text-[#B1BAD3] font-normal cursor-default">
                    The cursor is only iterated over when the game being played
                    requires the generation of more than 8 (32 bytes / 4 bytes)
                    possible outcomes. For example: when we need to use more than 8
                    cards in a game of blackjack.
                </p>

                <p className="mt-4 text-[#B1BAD3] font-normal cursor-default">
                    The cursor starts as 0 and gets increased by 1 every time the 32
                    bytes are returned by the HMAC_SHA256 function. If we don't
                    require more than 8 random numbers to be generated for the game
                    events, then the curser does not increment as there is no need
                    to generate any additional possible game outcomes.
                </p>
            </div>
            <div className="mt-4">
                <p className="font-semibold leading-[1.5] text-left text-base sm:text-base md:text-lg lg:text-xlflex items-center space-x-2">
                    Games with more than 1 incremental number:
                </p>
                <li className="text-[#B1BAD3] mt-4 mb-2">
                    Hilo (Unlimited to cover required amount of cards)
                </li>

                <li className="text-[#B1BAD3] mb-2">
                    Keno (2 increments for every game due to 10 possible outcomes)
                </li>

                <li className="text-[#B1BAD3] mb-2">
                    Mines (3 increments per game for 24 possible bomb locations)
                </li>

                <li className="text-[#B1BAD3] mb-2">
                    Pump (3 increments per game for 24 possible pop chances)
                </li>

                <li className="text-[#B1BAD3] mb-2">
                    Plinko (2 increments per game to cover possible 16 decisions)
                </li>

                <li className="text-[#B1BAD3] mb-2">
                    Blackjack (Unlimited to cover required amount of cards)
                </li>

                <li className="text-[#B1BAD3] mb-2">
                    Video Poker (7 increments to generate 52 possible cards in a
                    full deck)
                </li>

                <li className="text-[#B1BAD3] mb-2">
                    Diamond Poker (2 increments to cover 10 diamonds: 5 per
                    player/dealer)
                </li>

                <li className="text-[#B1BAD3] mb-2">
                    Slots (The incremental number is only utilised for bonus rounds)
                </li>
            </div>
            <div className="mt-4">
                <p className="font-semibold leading-[1.5] text-left text-base sm:text-base md:text-lg lg:text-xlflex items-center space-x-2 mb-3">
                    Games with only 1 incremental number (represented as default
                    value 0):
                </p>

                <li className="text-[#B1BAD3] mb-2">Dice</li>

                <li className="text-[#B1BAD3] mb-2">Limbo</li>

                <li className="text-[#B1BAD3] mb-2">Wheel</li>

                <li className="text-[#B1BAD3] mb-2">Baccarat</li>

                <li className="text-[#B1BAD3] mb-2">Roulette</li>

                <li className="text-[#B1BAD3] mb-2">Diamonds</li>

                <li className="text-[#B1BAD3] mb-2">Cases</li>
            </div>
        </div>
    )
}

export default Implementation